
package InterfazGrafica;

import Controladora.Controladora;
import Controladora.InterfazException;
import Controladora.InterfazNuevoPed;

import empresa.Empresa;
import empresa.EmpresaException;
import empresa.Maquina;
import empresa.Pedido;

import java.awt.event.ActionListener;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.Calendar;

import java.util.GregorianCalendar;

import java.util.HashMap;

import java.util.Iterator;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * Clase NuevoPedido.
 * Ventana de ingreso de datos para cargar nuevo pedido.
 */
public class NuevoPedido 
  extends javax.swing.JFrame implements InterfazNuevoPed
{
  private HashMap<Integer, Maquina> maquinas;
  
    /**
     * Constructor ventana NuevoPedido.
     * Precondicion:
     * maquinas no puede ser nulo.
     * PostCondicion:
     * 
     * @param maquinas
     * HashMap: Listado de las maquinas disponibles en la
     * empresa.
     */
    public NuevoPedido(HashMap<Integer, Maquina> maquinas)
    {
        assert(maquinas != null) : ("Listado maquinas nulo.");
        initComponents();
        setLocationRelativeTo(null);
        this.maquinas = maquinas;
        inicializarComponentes();
    }
    
    /*
     * Getters para eventual Test de GUI
     */


    public JButton getAgregar() {
        return agregar;
    }

    public JComboBox<String> getComboMaq() {
        return comboMaq;
    }

    public JTextField getFechaSol() {
        return fechaSol;
    }

    public JTextArea getJTextArea1() {
        return jTextArea1;
    }

    public JTextField getTextCantMaq() {
        return textCantMaq;
    }

    public JButton getVolver() {
        return volver;
    }

    /*
     * **********************************************
     */
  
    /**
     * metodo inicializarComponentes
     * Inicializa los componentes de la ventana.
     */
    private void inicializarComponentes(){
        agregar.setActionCommand(InterfazNuevoPed.AGREGAR);
        volver.setActionCommand(InterfazNuevoPed.VOLVER);
        jTextArea1.setEditable(false);
        cargarCombo();
        jTextArea1.setText(maquinas.get(Integer.parseInt((String) comboMaq.getSelectedItem())).getDescripcion());
    }
  
    /**
     * metodo cargarCombo
     * carga el comboBox con todas las opciones posibles de maquinas.
     */
    private void cargarCombo(){
        comboMaq.removeAllItems();
        Iterator<Maquina> itMaq = maquinas.values().iterator();
        while(itMaq.hasNext())
            comboMaq.addItem("" + itMaq.next().getCodigo());
    }
  
    @Override
    public void mostrar(){
        this.setVisible(true);
    }
  
    @Override
    public void ocultar(){
        this.setVisible(false);
    }
  
    @Override
    public void cerrar(){
        this.dispose();
    }
  
    @Override
    public int getCodigoMaquina()
        throws NumberFormatException, InterfazException
    {
        int codigo = Integer.parseInt((String) comboMaq.getSelectedItem());
        if(codigo < 1 || codigo > 999999)
            throw new InterfazException("Codigo fuera de rango.");
        return codigo;
    }
  
    @Override
    public void setControlador(Controladora c){
        assert(c != null) : ("Contoladora nula");
        volver.addActionListener(c);
        agregar.addActionListener(c);
    }
  
    @Override
    public int getCantidad()
        throws NumberFormatException, InterfazException
    {
        int cantidad = Integer.parseInt(textCantMaq.getText());
        if(cantidad < 1)
            throw new InterfazException("Cantidad debe ser mayor que cero.");
        return cantidad;
    }
  
    @Override
    public Calendar getFecha()
        throws ParseException, InterfazException
    {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Calendar fecha = Calendar.getInstance();
        fecha.setTime(sdf.parse(fechaSol.getText()));
        if(fecha.before(GregorianCalendar.getInstance()))
            throw new InterfazException("Fecha solicitada en el pasado.");
        return fecha;
    }
  
  

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textCantMaq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaSol = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        comboMaq = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Pedido"));

        jLabel3.setText("Codigo maquina:");

        jLabel4.setText("Cantidad de maquinas:");

        jLabel5.setText("Fecha solicitada por Ventas:");

        agregar.setText("Agregar Pedido");

        volver.setText("Volver");

        comboMaq.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboMaqPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setText("Descripcion:");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCantMaq, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(fechaSol)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(comboMaq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCantMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fechaSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(volver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    /**
     * Refresca la ventana en funcion del item que se selecciono
     * en el comboBox.
     */
    private void comboMaqPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboMaqPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jTextArea1.setText(maquinas.get(Integer.parseInt((String) comboMaq.getSelectedItem())).getDescripcion());
    }//GEN-LAST:event_comboMaqPopupMenuWillBecomeInvisible

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(NuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(NuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(NuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(NuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> comboMaq;
    private javax.swing.JTextField fechaSol;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textCantMaq;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
